### ISSUE TITLE
Two Corpora Alignment

### ISSUE THREAD

**Issue by simonefrancia** [acrule/text_align#1]
Hi, 
we are facing many approaches to align two corpora texts, and we are asking if this repo could help us. Our task should work in this way:

Corpus 1
```
hello my name is Simone \n and i live in Manchester
```

Corpus 2
```hello my name is Sara and hello```

Result must be this alignment:

```hello my name is Simone``` -> ```hello my name is Sara```
```and i live in Manchester``` -> ```and hello```

Can your repo be helpful for my purpose? 
Thanks

**Comment by acrule** [comment]
This repo has an implementation of a modified Levenstein distance calculator. It would not do the fuzzy matching you give in your example, but it would look for exact matches. Given your examples:

`hello my name is` -> `hello my name is`
`and` -> `and`

The names Simone and Sara would not match, nor would "i live in Manchester" and "hello".

**Comment by simonefrancia** [comment]
Thanks for response!
Have you ever seen in your experience a fuzzy matcher like in my example?
Thanks a lot
